Make xml parsing work for python 2.7
Without this patch, you get exceptions like this:

Traceback (most recent call last):
  File "/home/pi/dist/pi/wemo.py", line 20, in _scan_once
    devices = pywemo.discover_devices()
  File "/home/pi/dist/third_party/pywemo/upnp.py", line 97, in discover_devices
    found_location)
  File "/home/pi/dist/third_party/pywemo/upnp.py", line 118, in device_from_uuid_and_location
    return Switch(location)
  File "/home/pi/dist/third_party/pywemo/ouimeaux_device/__init__.py", line 32, in __init__
    service = Service(svc, base_url)
  File "/home/pi/dist/third_party/pywemo/ouimeaux_device/api/service.py", line 69, in __init__
    self._svc_config = serviceParser.parseString(xml.content).actionList
  File "/home/pi/dist/third_party/pywemo/ouimeaux_device/api/xsd/service.py", line 1583, in parseString
    doc = parsexml_(StringIO(inString.decode("UTF-8")))
  File "/home/pi/dist/third_party/pywemo/ouimeaux_device/api/xsd/service.py", line 64, in parsexml_
    doc = etree_.parse(*args, **kwargs)
  File "<string>", line 62, in parse
  File "<string>", line 38, in parse
ParseError: no element found: line 1, column 0

Apparently, this is caused py passing unicode strings to elementree in python 2.7.  Passing ByteIOs works in both 2 and 3:

http://stackoverflow.com/questions/3418262/python-unicode-and-elementtree-parse